name: flutter_advanced_drop_down
description: "An advanced and customizable dropdown widget for Flutter applications, offering enhanced functionality and flexibility."
version: 0.5.0
homepage: https://github.com/nimr77/flutter_advanced_drop_down

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: 